#Packages used for the anaylsis#
##in Folder: delete the# Load packages -----------------------------------------------------------
require(MASS)
require(nlme)
library(lattice)
library(lme4) 

library(ggplot2)
library(corrplot) #correlation plot
library(reshape2)
library(ggplot2)
library(dplyr)
library(psych)

library(tidyverse)
library(lme4)
library(ggsci)
library(see)
library(cowplot)
library(withr)

library(dplyr)
library(lme4)
library(tidyr)
library(dtplyr)
library(stats)
library(broom)
library(glmmTMB)
library(ggplot2)
library(sjPlot)
library(performance)
library(predictmeans)
library(influence.ME)
library(PBImisc)
library(boxcoxmix)
library(MuMIn)
library(car)
library(officer)
library(flextable)
library(writexl)
library(emmeans)
library(stringr)
library(dplyr)
library(tidyverse)
library(parallel) 
library(readxl)
library(here)
library(showtext)
library(ggplot2)
library(dplyr)
library(Cairo)
library(ggbreak)
library(plotrix)